name: E2E Regression Tests

on: 
  push:
    branches: [main]
    paths:
      - '01-Gaps-Multienv/**' 
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Instalar Dependencias
        run:  |
          python -m pip install --upgrade pip
          if [ -f 01-Gaps-Multienv/requirements.txt ]; then pip install -r 01-Gaps-Multienv/requirements.txt; else pip install pytest python-dotenv; fi

      - name: Ejecutar Tests en QA (Por Defecto)
        env:
          ENV: qa
          BASE_URL: https://api.github.com/emojis
          API_TOKEN: ${{ secrets.QA_API_TOKEN }}
        run: python -m pytest -v -s
